### ISSUE TITLE
Does this work with latest Ember CLI?

### ISSUE THREAD

**Issue by jsmestad** [SpikedKira/ember-simple-crud#1]
Wanted to ask before jumping in. The demo site has older versions of Ember listed (even asks to upgrade versions) and I see 'initial commit' messages stating version of Ember CLI v1.13.x

Also does `ember g crud-root` support pod structure?

**Comment by SpikedKira** [comment]
Should work just fine with anything 1.13.8+
I have not explicitly tested though

**Comment by SpikedKira** [comment]
pod structure is not currently supported due to the RFC for the new revised pods
